# Generated by Django 3.1.12 on 2021-06-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('keyword', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('category', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
    ]
